//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allot_adjunct
    {
        public int adjunctid { get; set; }
        public string idcardbefore { get; set; }
        public string idcardback { get; set; }
        public string idcardhalfbody { get; set; }
        public string bankcardbefore { get; set; }
        public string bankcardback { get; set; }
        public string license { get; set; }
        public string contract { get; set; }
        public Nullable<int> sid { get; set; }
        public string cateringliscens { get; set; }
        public string shopinphoto { get; set; }
        public string shopdoorphoto { get; set; }
        public Nullable<bool> type { get; set; }
        public string istongbu { get; set; }
        public string msg { get; set; }
        public string ismemtongbu { get; set; }
        public string memmsg { get; set; }
    }
}
