//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allot_agent_qrcode_num
    {
        public int agentqrcodeid { get; set; }
        public Nullable<int> dcnum { get; set; }
        public Nullable<int> xcxnum { get; set; }
        public Nullable<int> fknum { get; set; }
        public Nullable<int> dqbnum { get; set; }
        public Nullable<int> dcysnum { get; set; }
        public Nullable<int> xcxysnum { get; set; }
        public Nullable<int> fkysnum { get; set; }
        public Nullable<int> dqbysnum { get; set; }
        public string createdate { get; set; }
        public Nullable<int> agentid { get; set; }
        public string operatetime { get; set; }
        public string operater { get; set; }
    }
}
