//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allot_tixian
    {
        public int id { get; set; }
        public Nullable<int> agentid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> adminid { get; set; }
        public Nullable<decimal> jine { get; set; }
        public string sqtime { get; set; }
        public string optime { get; set; }
        public Nullable<bool> status { get; set; }
        public string comm { get; set; }
    }
}
