//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allot_statistics
    {
        public int statisticsid { get; set; }
        public Nullable<int> agentid { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<decimal> sumallot { get; set; }
        public Nullable<int> subsidynum { get; set; }
        public Nullable<decimal> sumsubsidy { get; set; }
        public string month { get; set; }
    }
}
