//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allot_agent
    {
        public int agentid { get; set; }
        public string agentname { get; set; }
        public string addr { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string signer { get; set; }
        public string legaler { get; set; }
        public string phone { get; set; }
        public string bankcode { get; set; }
        public string bankname { get; set; }
        public string bankman { get; set; }
        public string bankno { get; set; }
        public string banktype { get; set; }
        public Nullable<decimal> payratio { get; set; }
        public Nullable<decimal> cardratio { get; set; }
        public Nullable<int> pagentid { get; set; }
        public Nullable<int> countqrcode { get; set; }
        public string saleman { get; set; }
        public string iscan { get; set; }
        public Nullable<int> validitydate { get; set; }
        public string signdate { get; set; }
        public string createdate { get; set; }
        public string agentcode { get; set; }
        public string isdel { get; set; }
        public string auditstate { get; set; }
        public string issolo { get; set; }
        public string solodate { get; set; }
        public string agentlevel { get; set; }
        public Nullable<decimal> selfrate { get; set; }
    }
}
