//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allot_clear_zyhfw
    {
        public int id { get; set; }
        public Nullable<int> agentid { get; set; }
        public Nullable<int> topagentid { get; set; }
        public Nullable<int> dcshopnum { get; set; }
        public Nullable<int> ddshopnum { get; set; }
        public Nullable<decimal> fuwumoney { get; set; }
        public Nullable<sbyte> state { get; set; }
        public string cleartime { get; set; }
        public string createdate { get; set; }
        public Nullable<int> oprateuser { get; set; }
        public string month { get; set; }
    }
}
