//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allot_agent_qrcode
    {
        public int agentqrcodeid { get; set; }
        public Nullable<int> sendnum { get; set; }
        public string createdate { get; set; }
        public string usetype { get; set; }
        public Nullable<int> agentid { get; set; }
        public Nullable<int> operater { get; set; }
        public Nullable<sbyte> isprint { get; set; }
    }
}
