//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bc_shop
    {
        public int bshopkey { get; set; }
        public string account { get; set; }
        public string key { get; set; }
        public string bshopname { get; set; }
        public Nullable<sbyte> state { get; set; }
        public Nullable<sbyte> enable { get; set; }
        public Nullable<sbyte> isdel { get; set; }
        public string phone { get; set; }
        public string username { get; set; }
        public string idcard { get; set; }
        public string bankno { get; set; }
        public string bankname { get; set; }
        public string createdate { get; set; }
        public string sheng { get; set; }
        public string shi { get; set; }
        public string bankcode { get; set; }
    }
}
