//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bc_shop_account
    {
        public int id { get; set; }
        public string orderid { get; set; }
        public Nullable<int> bshopkey { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string paymethod { get; set; }
        public Nullable<sbyte> state { get; set; }
        public string createdate { get; set; }
        public string remark { get; set; }
        public Nullable<sbyte> isclear { get; set; }
    }
}
