//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cf_meal
    {
        public string cfmealkey { get; set; }
        public string createDate { get; set; }
        public Nullable<int> shopkey { get; set; }
        public int tableNo { get; set; }
        public Nullable<int> isComplete { get; set; }
        public Nullable<int> isRecomment { get; set; }
        public string serialNo { get; set; }
        public string redPackageCode { get; set; }
        public string exceptionPlan { get; set; }
        public string exceptionRemark { get; set; }
        public string payMemberkey { get; set; }
        public string recommentMemberkey { get; set; }
        public string useHbCode { get; set; }
        public string jiucanno { get; set; }
        public string merge { get; set; }
        public Nullable<int> peoples { get; set; }
        public Nullable<bool> isfree { get; set; }
        public Nullable<bool> issign { get; set; }
        public Nullable<decimal> zexception { get; set; }
        public Nullable<int> shopuserid { get; set; }
    
        public virtual shop shop { get; set; }
    }
}
