//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_agent_balancetype
    {
        public int tid { get; set; }
        public Nullable<int> agentid { get; set; }
        public Nullable<decimal> t0 { get; set; }
        public Nullable<decimal> t1 { get; set; }
        public Nullable<decimal> card { get; set; }
        public Nullable<sbyte> ist0 { get; set; }
        public Nullable<decimal> quick { get; set; }
    }
}
