//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_book_orders
    {
        public int bid { get; set; }
        public Nullable<bool> type { get; set; }
        public string jctime { get; set; }
        public string addtime { get; set; }
        public string comm { get; set; }
        public string address { get; set; }
        public string linkman { get; set; }
        public string linktel { get; set; }
        public string sex { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> shopkey { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<sbyte> usepeoples { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> realamount { get; set; }
        public Nullable<int> couponid { get; set; }
        public Nullable<decimal> youhui { get; set; }
        public string orderno { get; set; }
        public Nullable<int> paytype { get; set; }
        public string payuser { get; set; }
        public string successtime { get; set; }
        public Nullable<bool> ist0 { get; set; }
        public string reorderno { get; set; }
        public Nullable<sbyte> origin { get; set; }
        public string msg { get; set; }
        public Nullable<decimal> packageFee { get; set; }
        public Nullable<decimal> serviceFee { get; set; }
        public Nullable<decimal> activityTotal { get; set; }
        public Nullable<decimal> shopPart { get; set; }
        public Nullable<decimal> pingtaiPart { get; set; }
        public string mtorderid { get; set; }
        public string shippingstate { get; set; }
        public string dispatcherName { get; set; }
        public string dispatcherPhone { get; set; }
        public string elmshopid { get; set; }
        public Nullable<decimal> deliverFee { get; set; }
        public string deliveryGeo { get; set; }
        public Nullable<sbyte> cardtype { get; set; }
    }
}
