//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_book_order_items
    {
        public int id { get; set; }
        public Nullable<int> itemkey { get; set; }
        public Nullable<int> guigeid { get; set; }
        public Nullable<decimal> price { get; set; }
        public string addtime { get; set; }
        public Nullable<int> num { get; set; }
        public string orderno { get; set; }
        public string name { get; set; }
    }
}
