//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_card_tongji
    {
        public int id { get; set; }
        public Nullable<int> shopid { get; set; }
        public Nullable<decimal> pingtaimoney { get; set; }
        public Nullable<decimal> zonge { get; set; }
        public Nullable<decimal> shopmoney { get; set; }
        public string addtime { get; set; }
        public Nullable<decimal> yitie { get; set; }
        public Nullable<decimal> chargemoney { get; set; }
        public Nullable<decimal> gain { get; set; }
    }
}
