//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_card_userecord
    {
        public int recordid { get; set; }
        public Nullable<int> cardid { get; set; }
        public string usetime { get; set; }
        public Nullable<int> shopkey { get; set; }
        public Nullable<decimal> consume { get; set; }
        public string cfmealkey { get; set; }
        public Nullable<int> type { get; set; }
        public string addtime { get; set; }
        public Nullable<decimal> pconsume { get; set; }
        public Nullable<decimal> smoney { get; set; }
        public Nullable<decimal> gain { get; set; }
        public string orderno { get; set; }
    }
}
