//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_card_charges
    {
        public int chargeid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> shopid { get; set; }
        public string orderno { get; set; }
        public string addtime { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> paytype { get; set; }
        public Nullable<int> ruleid { get; set; }
        public Nullable<int> baoxian { get; set; }
        public string mealkey { get; set; }
        public string payuser { get; set; }
        public string successtime { get; set; }
        public Nullable<bool> isdian { get; set; }
        public Nullable<sbyte> cardtype { get; set; }
    }
}
