//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_coupons
    {
        public int couponid { get; set; }
        public string cname { get; set; }
        public string cdesc { get; set; }
        public string sdate { get; set; }
        public string edate { get; set; }
        public Nullable<int> isonlineok { get; set; }
        public Nullable<int> shopid { get; set; }
        public Nullable<int> ifmoney { get; set; }
        public Nullable<int> okjian { get; set; }
        public string addtime { get; set; }
        public string istogether { get; set; }
        public string memtogether { get; set; }
        public string extendway { get; set; }
        public Nullable<decimal> minmoney { get; set; }
        public Nullable<int> isdian { get; set; }
        public Nullable<int> ismarketing { get; set; }
        public Nullable<decimal> maxmoney { get; set; }
        public Nullable<int> maxnum { get; set; }
    }
}
