//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_false_data
    {
        public int id { get; set; }
        public Nullable<System.DateTime> paydate { get; set; }
        public string billno { get; set; }
        public string isexception { get; set; }
        public string paytype { get; set; }
        public Nullable<decimal> realpay { get; set; }
        public Nullable<int> shopkey { get; set; }
    }
}
