//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_pay_channels
    {
        public int id { get; set; }
        public string channelname { get; set; }
        public Nullable<bool> enable { get; set; }
        public Nullable<decimal> t0rate { get; set; }
        public Nullable<decimal> t1rate { get; set; }
        public Nullable<decimal> krate { get; set; }
        public string addtime { get; set; }
        public Nullable<decimal> mint0rate { get; set; }
        public Nullable<decimal> mint1rate { get; set; }
        public Nullable<decimal> minkrate { get; set; }
    }
}
