//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_rate_actives
    {
        public int activeid { get; set; }
        public Nullable<decimal> active_rate { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string createdate { get; set; }
        public Nullable<sbyte> type { get; set; }
        public string actname { get; set; }
        public Nullable<int> ifmoney { get; set; }
        public Nullable<decimal> dactive_rate { get; set; }
    }
}
