//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_shop_wxpay
    {
        public int wxpayid { get; set; }
        public string mch_id { get; set; }
        public string key { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string opratetime { get; set; }
        public string oprater { get; set; }
        public string cardmchid { get; set; }
        public string cardmchkey { get; set; }
        public Nullable<bool> isdel { get; set; }
    }
}
