//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_sys_consts
    {
        public int id { get; set; }
        public Nullable<decimal> shopmemrate { get; set; }
        public Nullable<decimal> tixianrate { get; set; }
        public Nullable<decimal> consumerate { get; set; }
        public Nullable<decimal> t0balancerate { get; set; }
        public Nullable<decimal> balancerate { get; set; }
        public Nullable<decimal> balrate { get; set; }
        public Nullable<decimal> weixinbalrate { get; set; }
        public Nullable<decimal> minsginrate { get; set; }
        public Nullable<decimal> mincardrate { get; set; }
        public Nullable<decimal> xybalancerate { get; set; }
        public Nullable<decimal> xybalrate { get; set; }
        public Nullable<decimal> mint0rate { get; set; }
        public Nullable<decimal> dxybalancerate { get; set; }
        public Nullable<decimal> kuait0balancerate { get; set; }
        public Nullable<decimal> kuaimint0rate { get; set; }
        public Nullable<decimal> minkuaijiet0tshop { get; set; }
        public Nullable<decimal> defaultkuaijiet0 { get; set; }
    }
}
