//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_shop_account
    {
        public int saccountid { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string createdate { get; set; }
        public string orderno { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<decimal> brokerage { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string ratetype { get; set; }
        public string isxingye { get; set; }
        public string type { get; set; }
        public string isonline { get; set; }
        public string issao { get; set; }
        public Nullable<int> paytype { get; set; }
        public Nullable<bool> isdian { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> puserid { get; set; }
        public Nullable<bool> isrong { get; set; }
        public Nullable<bool> ist0 { get; set; }
        public Nullable<decimal> fmoney { get; set; }
        public Nullable<bool> isact { get; set; }
        public Nullable<int> cashier { get; set; }
        public Nullable<int> waiter { get; set; }
        public Nullable<bool> iskuai { get; set; }
        public Nullable<bool> issever { get; set; }
        public Nullable<sbyte> cardtype { get; set; }
        public Nullable<int> chaneltype { get; set; }
    }
}
