//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_shop_signusers
    {
        public int id { get; set; }
        public string name { get; set; }
        public string telno { get; set; }
        public Nullable<int> maxusenums { get; set; }
        public Nullable<decimal> maxprice { get; set; }
        public string addtime { get; set; }
        public Nullable<int> signnums { get; set; }
        public Nullable<decimal> signmoney { get; set; }
        public string lasttime { get; set; }
        public Nullable<bool> state { get; set; }
        public Nullable<int> shopkey { get; set; }
    }
}
