//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_shop_sendmsg
    {
        public int sendlogid { get; set; }
        public Nullable<int> shopkey { get; set; }
        public Nullable<int> num { get; set; }
        public string audit { get; set; }
        public string state { get; set; }
        public string createdate { get; set; }
        public string msg { get; set; }
        public Nullable<int> couponid { get; set; }
    }
}
