//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_shop_service_msg
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> shopkey { get; set; }
        public Nullable<int> suserid { get; set; }
        public Nullable<int> tableposkey { get; set; }
        public string msg { get; set; }
        public string addtime { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
