//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_tuijian
    {
        public int tjid { get; set; }
        public Nullable<int> peoplenum { get; set; }
        public string ren { get; set; }
        public string liyou { get; set; }
        public Nullable<int> afternum { get; set; }
        public Nullable<int> afteritem { get; set; }
        public Nullable<int> timesbyday { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> operater { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string items { get; set; }
    }
}
