//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_wx_memcard
    {
        public int wxmemcardid { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string wxcardid { get; set; }
        public string wxcardcode { get; set; }
        public string wxcardtype { get; set; }
        public string cardtype { get; set; }
        public string createdate { get; set; }
        public Nullable<int> couponid { get; set; }
        public string openid { get; set; }
        public Nullable<int> isdian { get; set; }
    }
}
