//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_set
    {
        public int itemsetkey { get; set; }
        public Nullable<int> tcItemKey { get; set; }
        public Nullable<int> itemkey { get; set; }
        public Nullable<int> itemnum { get; set; }
        public Nullable<int> guigeid { get; set; }
    }
}
