//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_standard
    {
        public int standardkey { get; set; }
        public Nullable<int> itemKey { get; set; }
        public string standardname { get; set; }
        public Nullable<decimal> sprice { get; set; }
        public Nullable<decimal> sagioprice { get; set; }
        public Nullable<sbyte> state { get; set; }
    }
}
