//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item_category()
        {
            this.item = new HashSet<item>();
            this.item_category_map = new HashSet<item_category_map>();
        }
    
        public int itemcategorykey { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string itemCategoryCode { get; set; }
        public string name { get; set; }
        public string instructions { get; set; }
        public string img { get; set; }
        public Nullable<int> enable { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> isDel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item> item { get; set; }
        public virtual shop shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_category_map> item_category_map { get; set; }
    }
}
