//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.cf_detail = new HashSet<cf_detail>();
            this.shop_car = new HashSet<shop_car>();
            this.shop_item_record = new HashSet<shop_item_record>();
            this.item_category_map = new HashSet<item_category_map>();
            this.item_comment = new HashSet<item_comment>();
        }
    
        public int itemkey { get; set; }
        public string itemCode { get; set; }
        public Nullable<int> itemType { get; set; }
        public Nullable<int> itemcategorykey { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string name { get; set; }
        public string introduce { get; set; }
        public string thumb { get; set; }
        public Nullable<int> place { get; set; }
        public string imgs { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> discountPrice { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<int> stockNum { get; set; }
        public Nullable<int> soldNum { get; set; }
        public string unit { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> isShowIndex { get; set; }
        public Nullable<int> isDel { get; set; }
        public Nullable<int> recommentNum { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
        public Nullable<int> isSet { get; set; }
        public Nullable<int> isStandard { get; set; }
        public Nullable<double> agioprice { get; set; }
        public Nullable<int> minnum { get; set; }
        public Nullable<int> islikenum { get; set; }
        public Nullable<int> unlikenum { get; set; }
        public Nullable<int> isprint { get; set; }
        public Nullable<int> isprintset { get; set; }
        public Nullable<int> storagenum { get; set; }
        public Nullable<sbyte> selebyunit { get; set; }
        public Nullable<sbyte> ispayagio { get; set; }
        public Nullable<sbyte> ismust { get; set; }
        public Nullable<sbyte> isware { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cf_detail> cf_detail { get; set; }
        public virtual item_category item_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shop_car> shop_car { get; set; }
        public virtual shop shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shop_item_record> shop_item_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_category_map> item_category_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_comment> item_comment { get; set; }
    }
}
