//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post()
        {
            this.post_power = new HashSet<post_power>();
        }
    
        public int postkey { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string postCode { get; set; }
        public string postName { get; set; }
        public Nullable<int> enable { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> isDel { get; set; }
    
        public virtual shop shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post_power> post_power { get; set; }
        public virtual shop shop1 { get; set; }
    }
}
