//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class print_main
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public print_main()
        {
            this.print_info = new HashSet<print_info>();
        }
    
        public int printmainkey { get; set; }
        public Nullable<int> memberkey { get; set; }
        public Nullable<int> isPrint { get; set; }
        public Nullable<int> autoRecvOrder { get; set; }
        public Nullable<int> autoPrint { get; set; }
    
        public virtual member member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<print_info> print_info { get; set; }
    }
}
