//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qr_code_batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qr_code_batch()
        {
            this.qr_code = new HashSet<qr_code>();
        }
    
        public int qrcodebatchkey { get; set; }
        public Nullable<int> shopkey { get; set; }
        public Nullable<int> num { get; set; }
        public string batchNoStr { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string batchCode { get; set; }
        public string saveurl { get; set; }
        public string type { get; set; }
        public Nullable<int> agentid { get; set; }
        public string usetype { get; set; }
        public Nullable<int> userid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qr_code> qr_code { get; set; }
        public virtual shop shop { get; set; }
    }
}
