//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qr_code
    {
        public int qrcodekey { get; set; }
        public Nullable<int> qrcodebatchkey { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> isUsed { get; set; }
        public Nullable<int> tableposkey { get; set; }
        public Nullable<int> agentid { get; set; }
        public Nullable<int> isdian { get; set; }
    
        public virtual qr_code_batch qr_code_batch { get; set; }
        public virtual shop shop { get; set; }
    }
}
