//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_car
    {
        public int shopcarkey { get; set; }
        public Nullable<int> shopkey { get; set; }
        public Nullable<int> tableNo { get; set; }
        public Nullable<int> itemkey { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> memberkey { get; set; }
        public Nullable<int> guigeid { get; set; }
        public string zuofa { get; set; }
    
        public virtual item item { get; set; }
        public virtual shop shop { get; set; }
    }
}
