//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage_depotin
    {
        public int depotinid { get; set; }
        public string createdate { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> depotid { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string dutyperson { get; set; }
        public string deliveryman { get; set; }
        public string deliveryphone { get; set; }
        public string driver { get; set; }
        public string platenum { get; set; }
        public Nullable<sbyte> type { get; set; }
    }
}
