//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage_crude
    {
        public int crudeid { get; set; }
        public string crudename { get; set; }
        public string unit { get; set; }
        public string standard { get; set; }
        public string crudecode { get; set; }
        public string barcode { get; set; }
        public string createdate { get; set; }
        public Nullable<int> genreid { get; set; }
        public Nullable<int> shopkey { get; set; }
        public Nullable<sbyte> state { get; set; }
    }
}
