//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage_depotin_info
    {
        public int ininfoid { get; set; }
        public Nullable<int> depotinid { get; set; }
        public Nullable<int> crudeid { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> num { get; set; }
        public string productiondate { get; set; }
        public string validity { get; set; }
        public string backdate { get; set; }
        public string maker { get; set; }
        public string remarks { get; set; }
        public string supplier { get; set; }
    }
}
