//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_menu
    {
        public Nullable<int> userid { get; set; }
        public int menuid { get; set; }
        public string name { get; set; }
        public string keyurl { get; set; }
        public Nullable<int> sortno { get; set; }
        public Nullable<int> addtime { get; set; }
        public Nullable<int> fid { get; set; }
        public Nullable<bool> is_show { get; set; }
        public string type { get; set; }
        public string menu_icon { get; set; }
        public string code { get; set; }
    }
}
