//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_common_type
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> sort { get; set; }
        public string label { get; set; }
        public string label_eng { get; set; }
        public Nullable<int> cnt { get; set; }
        public Nullable<bool> showlink { get; set; }
        public Nullable<bool> showdel { get; set; }
        public Nullable<bool> changecid { get; set; }
        public Nullable<bool> showcont { get; set; }
        public Nullable<bool> showdoc { get; set; }
        public Nullable<bool> showpic { get; set; }
        public string otherlink { get; set; }
        public Nullable<bool> showvideo { get; set; }
        public Nullable<bool> showfile { get; set; }
        public Nullable<bool> showisrec { get; set; }
        public Nullable<bool> ctype { get; set; }
        public Nullable<bool> showabst { get; set; }
        public Nullable<bool> modifytime { get; set; }
    }
}
