//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_document
    {
        public int id { get; set; }
        public string title { get; set; }
        public string title_eng { get; set; }
        public string tag { get; set; }
        public string abst { get; set; }
        public string url { get; set; }
        public string content { get; set; }
        public Nullable<int> ctime { get; set; }
        public string author { get; set; }
        public Nullable<int> cid { get; set; }
        public string img { get; set; }
        public Nullable<int> hits { get; set; }
        public Nullable<int> pos { get; set; }
        public string doc { get; set; }
        public string swf { get; set; }
        public string video { get; set; }
        public Nullable<int> pid { get; set; }
        public string file { get; set; }
        public Nullable<int> isrec { get; set; }
        public string zhize { get; set; }
        public string jingli { get; set; }
        public string chengguo { get; set; }
        public Nullable<int> top { get; set; }
    }
}
