//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_pos
    {
        public int tableposkey { get; set; }
        public string qrCode { get; set; }
        public Nullable<int> tableNo { get; set; }
        public string tableName { get; set; }
        public Nullable<int> peopleNum { get; set; }
        public Nullable<int> shopkey { get; set; }
        public Nullable<int> state { get; set; }
        public string createDate { get; set; }
        public Nullable<int> enable { get; set; }
        public Nullable<int> isDel { get; set; }
        public Nullable<int> isRoom { get; set; }
        public Nullable<sbyte> peoples { get; set; }
        public Nullable<int> floorid { get; set; }
        public string opentime { get; set; }
        public Nullable<int> shopuserid { get; set; }
        public string shopusername { get; set; }
        public Nullable<decimal> tfuwu { get; set; }
    
        public virtual shop shop { get; set; }
    }
}
