//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turn_user_record
    {
        public int tureuserrecordkey { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string createDate { get; set; }
        public string endtime { get; set; }
        public Nullable<int> afteruser { get; set; }
        public Nullable<int> beforeuser { get; set; }
        public Nullable<decimal> pettycash { get; set; }
        public Nullable<decimal> overplus { get; set; }
        public Nullable<decimal> selfplus { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> youhui { get; set; }
        public Nullable<decimal> realpay { get; set; }
        public Nullable<decimal> zexception { get; set; }
        public Nullable<decimal> exception { get; set; }
        public Nullable<decimal> cashamount { get; set; }
        public Nullable<decimal> cashyouhui { get; set; }
        public Nullable<decimal> cashrealpay { get; set; }
        public Nullable<decimal> cashzexception { get; set; }
        public Nullable<decimal> cashexception { get; set; }
        public Nullable<decimal> freeamount { get; set; }
        public Nullable<int> freecount { get; set; }
    }
}
