//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianDianClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_dd_pocket_users
    {
        public long cnt { get; set; }
        public Nullable<decimal> aveprice { get; set; }
        public string name { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> shopkey { get; set; }
        public string icon { get; set; }
        public string tel { get; set; }
        public Nullable<int> cardid { get; set; }
        public string createdate { get; set; }
    }
}
